---
# This registers some new facts:
# * new_instance(str): short name for the newly created instance
# * new_instance_fqdn(str)
# * prefix_servers_info(dict, see openstack.cloud.server_info)
#
# and some internal usage ones:
# * image_id(str)
# * flavor_id(str)
# * security_groups(list[str])
# * security_group_name(str)
# * server_group_uuid(str)
# * network(str)
#
- name: Get existing prefxed instances info for the project
  openstack.cloud.server_info:
    auth: &openstack_auth
      auth_url: "{{openstack_auth_url}}"
      username: "{{openstack_username}}"
      password: "{{openstack_password}}"
      project_name: "{{openstack_project}}"
      user_domain_name: "{{openstack_user_domain_name}}"
      project_domain_name: "{{openstack_project_domain_name}}"
    server: "{{prefix}}*"
  register: prefix_servers_info

- name: Setting simple facts
  set_fact:
    # The string 'project' gets replacet with ****
    last_instance: "{{ (prefix_servers_info.openstack_servers | sort(attribute='name'))[-1]['name'] | replace('********', openstack_project)}}"
    new_instance: "{{prefix}}-{{ ((prefix_servers_info.openstack_servers | sort(attribute='name'))[-1]['name'].split('-')[-1] | int) + 1 }}"

    image_id: "{{ (prefix_servers_info.openstack_servers | sort(attribute='name'))[-1]['image']['id'] }}"
    flavor_id: "{{ (prefix_servers_info.openstack_servers | sort(attribute='name'))[-1]['flavor']['id'] }}"
    # TODO: The default security group gets replaced by
    # VALUE_SPECIFIED_IN_NO_LOG_PARAMETER for some reason in this case
    network: "{{ ((prefix_servers_info.openstack_servers | sort(attribute='name'))[-1]['security_groups'] | map(attribute='name') | flatten)[1:] }}"
    security_groups:
      - default
      - "{{security_group_name}}"


- name: Setting derived facts
  set_fact:
    new_instance_fqdn: "{{new_instance}}.{{cloud_domain}}"
    last_instance_fqdn: "{{last_instance}}.{{cloud_domain}}"

- debug:
    msg: "Starting new instance {{new_instance_fqdn}}"

- name: Start the new instance
  openstack.cloud.server:
    state: present
    auth:
      <<: *openstack_auth
    name: "{{new_instance}}"
    image: "{{image_id}}"
    flavor: "{{flavor_id}}"
    timeout: 300
    availability_zone: nova
    network: lan-flat-cloudinstances2b
    security_groups: "{{security_groups}}"
    auto_ip: false
    scheduler_hints:
      group: "{{server_group_uuid}}"

- name: Wait max 900 seconds for the VM to come up
  wait_for_connection:
    timeout: 900
  run_once: true
  delegate_to: "{{new_instance_fqdn}}"
